var chsSubreddit = {
"kind": "Listing",
"data": {
"modhash": "",
"children": [
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Alright ladies and gents, with the Iowa circus and New Hampshire primary over, you can bet your bottom dollar that we will see an influx of politically-related posts in &lt;a href=\"/r/Charleston\"&gt;/r/Charleston&lt;/a&gt;. &lt;/p&gt;\n\n&lt;p&gt;I felt obligated to make this post because the Bernie march Facebook page was reported, and it is just the first of many. Please only report posts that violate our rules, use your downvotes for disagreements. Don&amp;#39;t pay the troll toll.&lt;/p&gt;\n\n&lt;hr/&gt;\n\n&lt;p&gt;Many of us are aware political disagreements can bring out the best in all of us, so please consider both &lt;a href=\"https://www.reddit.com/r/Charleston/wiki/index#wiki_.2Fr.2Fcharleston_submission_rules\"&gt;our rules&lt;/a&gt;, as well as &lt;a href=\"https://www.reddit.com/wiki/reddiquette\"&gt;Reddit&amp;#39;s reddiquette&lt;/a&gt; when making posts.&lt;/p&gt;\n\n&lt;hr/&gt;\n\n&lt;p&gt;&lt;strong&gt;Here is what is OK&lt;/strong&gt;: &amp;lt;--(Please do not report)&lt;/p&gt;\n\n&lt;p&gt;Posting events such as &lt;a href=\"https://www.reddit.com/r/Charleston/comments/44xt4s/bernie_march_in_charleston_sc_this_saturday/\"&gt;this lawful right to assembly&lt;/a&gt; are fine. &lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;&lt;p&gt;Having an opinion is fine.&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Disagreeing with someone else&amp;#39;s opinion is fine.&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Having an upvote/downvote party is fine as long as a post or comment does/does not contribute to the discussion.&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Looking for volunteers to participate &lt;em&gt;locally&lt;/em&gt; in a political campaign is fine.&lt;/p&gt;&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;Etc... I am not your mother.&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;What is NOT OK&lt;/strong&gt;: &amp;lt;--(Please report)&lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;&lt;p&gt;Abusing the Report button on something you simply disagree with. Reports are &lt;strong&gt;not&lt;/strong&gt; super downvotes. &lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Trolling posts/comments/accounts primarily intended to provoke or defame supporters, candidates, or particular socioeconomic groups.&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Anything violating &lt;a href=\"https://www.reddit.com/r/Charleston/wiki/index#wiki_.2Fr.2Fcharleston_submission_rules\"&gt;the rules&lt;/a&gt; of &lt;a href=\"/r/Charleston\"&gt;/r/Charleston&lt;/a&gt; or the aforementioned &lt;a href=\"https://www.reddit.com/wiki/reddiquette\"&gt;reddiquette&lt;/a&gt;.&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Asking for reddit votes e.g. &amp;quot;Upboat if you like [Candidate]&amp;quot; while linking to a picture or their campaign site.&lt;/p&gt;&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;&lt;strong&gt;What may or may not be OK depending on the circumstances&lt;/strong&gt;:&lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;&lt;p&gt;Soapboxing for a particular candidate will likely be removed if reported. This is &lt;strong&gt;not&lt;/strong&gt; a political subreddit, it is a local one. If you are curious as to what this means, go to any of the candidate&amp;#39;s dedicated subreddits and read the titles of the top posts this week. Avoid that sort of thing here unless it pertains directly to the primaries here in South Carolina. &lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Reported items will be reviewed on a case-by-case basis.&lt;/p&gt;\n\n&lt;hr/&gt;&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;All that being said, please contact the moderators if you feel a post or comment was unnecessarily removed, or got caught in the spam filter.&lt;/p&gt;\n\n&lt;p&gt;As always, we rely on the community to report posts and comments that are in violation of the rules. The average user is the real moderator of &lt;a href=\"/r/Charleston\"&gt;/r/Charleston&lt;/a&gt;.&lt;/p&gt;\n\n&lt;p&gt;The goal here is to continue moderating our small corner of the site that represents Charleston for the great place it is. There is no intention to limit anyone&amp;#39;s right to free speech/assembly/right to vote/etc. We are just preemptively boarding up the windows for when the storm comes.&lt;/p&gt;\n\n&lt;p&gt;Please feel free to discuss anything and everything that you feel I have failed to mention in this post that you would like to see, or not see, in &lt;a href=\"/r/Charleston\"&gt;/r/Charleston&lt;/a&gt; as the primaries descend upon our fair state. &lt;/p&gt;\n\n&lt;hr/&gt;\n\n&lt;p&gt;&lt;strong&gt;Republican Primary\nSaturday, February 20, 2016&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;Democratic Primary\nSaturday, February 27, 2016&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href=\"https://info.scvotes.sc.gov/eng/voterinquiry/VoterInformationRequest.aspx?PageMode=VoterInfo\"&gt;Don&amp;#39;t know where to vote?&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Alright ladies and gents, with the Iowa circus and New Hampshire primary over, you can bet your bottom dollar that we will see an influx of politically-related posts in /r/Charleston. \n\nI felt obligated to make this post because the Bernie march Facebook page was reported, and it is just the first of many. Please only report posts that violate our rules, use your downvotes for disagreements. Don't pay the troll toll.\n___\nMany of us are aware political disagreements can bring out the best in all of us, so please consider both [our rules] (https://www.reddit.com/r/Charleston/wiki/index#wiki_.2Fr.2Fcharleston_submission_rules), as well as [Reddit's reddiquette](https://www.reddit.com/wiki/reddiquette) when making posts.\n\n___\n\n**Here is what is OK**: &lt;--(Please do not report)\n\nPosting events such as [this lawful right to assembly]  (https://www.reddit.com/r/Charleston/comments/44xt4s/bernie_march_in_charleston_sc_this_saturday/) are fine. \n\n* Having an opinion is fine.\n\n* Disagreeing with someone else's opinion is fine.\n\n* Having an upvote/downvote party is fine as long as a post or comment does/does not contribute to the discussion.\n\n* Looking for volunteers to participate *locally* in a political campaign is fine.\n\nEtc... I am not your mother.\n\n**What is NOT OK**: &lt;--(Please report)\n\n* Abusing the Report button on something you simply disagree with. Reports are **not** super downvotes. \n\n* Trolling posts/comments/accounts primarily intended to provoke or defame supporters, candidates, or particular socioeconomic groups.\n\n* Anything violating [the rules](https://www.reddit.com/r/Charleston/wiki/index#wiki_.2Fr.2Fcharleston_submission_rules) of /r/Charleston or the aforementioned [reddiquette](https://www.reddit.com/wiki/reddiquette).\n\n* Asking for reddit votes e.g. \"Upboat if you like [Candidate]\" while linking to a picture or their campaign site.\n\n**What may or may not be OK depending on the circumstances**:\n\n* Soapboxing for a particular candidate will likely be removed if reported. This is **not** a political subreddit, it is a local one. If you are curious as to what this means, go to any of the candidate's dedicated subreddits and read the titles of the top posts this week. Avoid that sort of thing here unless it pertains directly to the primaries here in South Carolina. \n\n* Reported items will be reviewed on a case-by-case basis.\n___\n\nAll that being said, please contact the moderators if you feel a post or comment was unnecessarily removed, or got caught in the spam filter.\n\nAs always, we rely on the community to report posts and comments that are in violation of the rules. The average user is the real moderator of /r/Charleston.\n\nThe goal here is to continue moderating our small corner of the site that represents Charleston for the great place it is. There is no intention to limit anyone's right to free speech/assembly/right to vote/etc. We are just preemptively boarding up the windows for when the storm comes.\n\nPlease feel free to discuss anything and everything that you feel I have failed to mention in this post that you would like to see, or not see, in /r/Charleston as the primaries descend upon our fair state. \n___\n**Republican Primary\nSaturday, February 20, 2016**\n\n**Democratic Primary\nSaturday, February 27, 2016**\n\n[Don't know where to vote?](https://info.scvotes.sc.gov/eng/voterinquiry/VoterInformationRequest.aspx?PageMode=VoterInfo)",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "455aop",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "pbmainiac3",
"media": null,
"score": 33,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 1,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": 1455142891,
"link_flair_css_class": null,
"author_flair_css_class": "mod",
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": true,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/455aop/rules_regarding_upcoming_sc_primaries/",
"locked": false,
"name": "t3_455aop",
"created": 1455170600,
"url": "https://www.reddit.com/r/Charleston/comments/455aop/rules_regarding_upcoming_sc_primaries/",
"author_flair_text": "mod",
"quarantine": false,
"title": "Rules Regarding Upcoming SC Primaries",
"created_utc": 1455141800,
"distinguished": "moderator",
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 33
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Welcome to our new &lt;strong&gt;weekly post&lt;/strong&gt; where we discuss any events or activities taking place this weekend in the Charleston area. You can find events by checking &lt;a href=\"http://www.charlestoncitypaper.com/charleston/EventSearch?narrowByDate=This%20Weekend\"&gt;Charleston City Paper&lt;/a&gt;, &lt;a href=\"http://chsbeer.org/events\"&gt;CHSBeer&lt;/a&gt;,  &lt;a href=\"http://chs-tonight.com/\"&gt;chs-tonight&lt;/a&gt;, &lt;a href=\"http://metronomecharleston.com/calendar/\"&gt;Metronome&lt;/a&gt;, &lt;a href=\"http://www.holycitysinner.com/events/\"&gt;HolyCitySinner&lt;/a&gt;, &lt;a href=\"http://www.postandcourier.com/section/search&amp;amp;facet.filter=Keywords:Things%20to%20Do\"&gt;Post &amp;amp; Courier&lt;/a&gt;, or &lt;a href=\"http://www.charlestoncvb.com/visitors/events_news/charleston-events/\"&gt;Charleston CVB&lt;/a&gt;. Please post a link to an event page for additional information (if possible).&lt;/p&gt;\n\n&lt;p&gt;The goal is simple: to generate some discussion, learn about what&amp;#39;s happening in the area, arrange impromptu meetups, and maybe help out anyone visiting for the weekend.&lt;/p&gt;\n\n&lt;p&gt;Thanks for participating! Any questions, &lt;a href=\"https://www.reddit.com/message/compose?to=%2Fr%2Fcharleston\"&gt;please ask the mods&lt;/a&gt;.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Welcome to our new **weekly post** where we discuss any events or activities taking place this weekend in the Charleston area. You can find events by checking [Charleston City Paper](http://www.charlestoncitypaper.com/charleston/EventSearch?narrowByDate=This%20Weekend), [CHSBeer](http://chsbeer.org/events),  [chs-tonight](http://chs-tonight.com/), [Metronome](http://metronomecharleston.com/calendar/), [HolyCitySinner](http://www.holycitysinner.com/events/), [Post &amp; Courier](http://www.postandcourier.com/section/search&amp;facet.filter=Keywords:Things%20to%20Do), or [Charleston CVB](http://www.charlestoncvb.com/visitors/events_news/charleston-events/). Please post a link to an event page for additional information (if possible).\n\nThe goal is simple: to generate some discussion, learn about what's happening in the area, arrange impromptu meetups, and maybe help out anyone visiting for the weekend.\n\nThanks for participating! Any questions, [please ask the mods](https://www.reddit.com/message/compose?to=%2Fr%2Fcharleston).\n",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": "TGIF!",
"id": "45771e",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "AutoModerator",
"media": null,
"score": 11,
"approved_by": null,
"over_18": false,
"hidden": false,
"preview": {
"images": [
{
"source": {
"url": "https://i.redditmedia.com/TjVs0b04DMddxkTXY6_DrxJJL2JSezOn2geOwhlqy7g.jpg?s=9610edfcef7d963e5a3c4431000a9128",
"width": 200,
"height": 200
},
"resolutions": [
{
"url": "https://i.redditmedia.com/TjVs0b04DMddxkTXY6_DrxJJL2JSezOn2geOwhlqy7g.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=625689bbbb152640753ae110bf415b4f",
"width": 108,
"height": 108
}
],
"variants": {},
"id": "Je4bqtZmh-W_FBqUqyUiOU51oUt2y3-RUGKLdSFid38"
}
]
},
"num_comments": 1,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": "tgif",
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"post_hint": "self",
"stickied": true,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/45771e/weekend_roundup_february_11_2016/",
"locked": false,
"name": "t3_45771e",
"created": 1455195825,
"url": "https://www.reddit.com/r/Charleston/comments/45771e/weekend_roundup_february_11_2016/",
"author_flair_text": "Robot Overlord",
"quarantine": false,
"title": "Weekend Roundup! February 11, 2016",
"created_utc": 1455167025,
"distinguished": "moderator",
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 11
}
},
{
"kind": "t3",
"data": {
"domain": "go.berniesanders.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "460zxf",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "seamslegit",
"media": null,
"score": 19,
"approved_by": null,
"over_18": false,
"hidden": false,
"preview": {
"images": [
{
"source": {
"url": "https://i.redditmedia.com/HwRKiNzrr3GDsMO6vw5CQcKpfTRpO_rTkrUYojNwqsQ.jpg?s=f9985a138084ad46244604bc28564357",
"width": 1200,
"height": 630
},
"resolutions": [
{
"url": "https://i.redditmedia.com/HwRKiNzrr3GDsMO6vw5CQcKpfTRpO_rTkrUYojNwqsQ.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=2ff45fdbf121488722b9adb929538c77",
"width": 108,
"height": 56
},
{
"url": "https://i.redditmedia.com/HwRKiNzrr3GDsMO6vw5CQcKpfTRpO_rTkrUYojNwqsQ.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=607659a96a3f1150501a76701fdbc134",
"width": 216,
"height": 113
},
{
"url": "https://i.redditmedia.com/HwRKiNzrr3GDsMO6vw5CQcKpfTRpO_rTkrUYojNwqsQ.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=54641bcbf40a21737bae6f6f23ff6fa9",
"width": 320,
"height": 168
},
{
"url": "https://i.redditmedia.com/HwRKiNzrr3GDsMO6vw5CQcKpfTRpO_rTkrUYojNwqsQ.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=5f8d67f86af770a11b5ce2379f35321a",
"width": 640,
"height": 336
},
{
"url": "https://i.redditmedia.com/HwRKiNzrr3GDsMO6vw5CQcKpfTRpO_rTkrUYojNwqsQ.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=e0017efd818389f44aed637cea5972d6",
"width": 960,
"height": 504
},
{
"url": "https://i.redditmedia.com/HwRKiNzrr3GDsMO6vw5CQcKpfTRpO_rTkrUYojNwqsQ.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=36d026acfca53b9b6718ad8a0d03b4ea",
"width": 1080,
"height": 567
}
],
"variants": {},
"id": "tj9IipqXnMQQcj0kN-gV38bj4mheGYGpk5sRCXp4H0k"
}
]
},
"num_comments": 5,
"thumbnail": "http://a.thumbs.redditmedia.com/ErogX1BDiHOPpAR9BX-K6S1WmHiRMhD8126FVVwCsj0.jpg",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"post_hint": "link",
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/460zxf/bernie_sanders_for_president_event_charleston/",
"locked": false,
"name": "t3_460zxf",
"created": 1455629050,
"url": "https://go.berniesanders.com/page/event/detail/townmeeting/49g",
"author_flair_text": null,
"quarantine": false,
"title": "Bernie Sanders for President | Event | Charleston Town Hall Meeting with Bernie Sanders on 2/16",
"created_utc": 1455600250,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 19
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Join First Friday Charleston for our March Networking Happy Hour/MeetUp! We&amp;#39;re headed to the Alley from 5:30 - 8:00 p.m. on Friday, March 4. &lt;/p&gt;\n\n&lt;p&gt;Parking is easy. Just around the corner from the venue in their giant lot. &lt;/p&gt;\n\n&lt;p&gt;If you haven&amp;#39;t made it to one of our events, it&amp;#39;s time to step up. \nStep up and help us reach our goal of 200 attendees!&lt;/p&gt;\n\n&lt;p&gt;We had over 160 people at our February event. Come meet some new people and get plugged into Charleston!&lt;/p&gt;\n\n&lt;p&gt;For more information and to RSVP, visit: &lt;a href=\"http://www.facebook.com/firstfridaycharleston\"&gt;www.facebook.com/firstfridaycharleston&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Join First Friday Charleston for our March Networking Happy Hour/MeetUp! We're headed to the Alley from 5:30 - 8:00 p.m. on Friday, March 4. \n\nParking is easy. Just around the corner from the venue in their giant lot. \n\nIf you haven't made it to one of our events, it's time to step up. \nStep up and help us reach our goal of 200 attendees!\n\nWe had over 160 people at our February event. Come meet some new people and get plugged into Charleston!\n\nFor more information and to RSVP, visit: www.facebook.com/firstfridaycharleston",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "460by4",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "89blazer",
"media": null,
"score": 10,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 1,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/460by4/march_networking_happy_hour/",
"locked": false,
"name": "t3_460by4",
"created": 1455619152,
"url": "https://www.reddit.com/r/Charleston/comments/460by4/march_networking_happy_hour/",
"author_flair_text": null,
"quarantine": false,
"title": "March Networking Happy Hour",
"created_utc": 1455590352,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 10
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Savannah is in the middle of a crime spree and a 28% poverty rate. A lot of people here think its all related to the low paying jobs in the tourism industry (Hotels and restaurants really). I&amp;#39;m looking for another city with similar economies (tourism, shipping) and my question to Charleston is: Where does your poverty come from and am I wrong to think that tourism can negatively affect the city?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Savannah is in the middle of a crime spree and a 28% poverty rate. A lot of people here think its all related to the low paying jobs in the tourism industry (Hotels and restaurants really). I'm looking for another city with similar economies (tourism, shipping) and my question to Charleston is: Where does your poverty come from and am I wrong to think that tourism can negatively affect the city?",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45x6we",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "glockazine",
"media": null,
"score": 11,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 25,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/45x6we/tourism_and_poverty_savannah_is_getting_severely/",
"locked": false,
"name": "t3_45x6we",
"created": 1455581788,
"url": "https://www.reddit.com/r/Charleston/comments/45x6we/tourism_and_poverty_savannah_is_getting_severely/",
"author_flair_text": null,
"quarantine": false,
"title": "Tourism and Poverty: Savannah is getting severely affected by tourism, y'all have a similar problem?",
"created_utc": 1455552988,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 11
}
},
{
"kind": "t3",
"data": {
"domain": "counton2.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45tkc0",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "sillybun99",
"media": null,
"score": 29,
"approved_by": null,
"over_18": false,
"hidden": false,
"preview": {
"images": [
{
"source": {
"url": "https://i.redditmedia.com/my7Y2tDiL5jzXoa6KGCuZGv7Cav3FRLXIjIdxw-z_7A.jpg?s=4f66e08e74163167a636057e80ca9674",
"width": 1200,
"height": 900
},
"resolutions": [
{
"url": "https://i.redditmedia.com/my7Y2tDiL5jzXoa6KGCuZGv7Cav3FRLXIjIdxw-z_7A.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=62514831256d94b6d5e9861dd1d6717c",
"width": 108,
"height": 81
},
{
"url": "https://i.redditmedia.com/my7Y2tDiL5jzXoa6KGCuZGv7Cav3FRLXIjIdxw-z_7A.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=4e4f911b0f1c73121e87c8956857f496",
"width": 216,
"height": 162
},
{
"url": "https://i.redditmedia.com/my7Y2tDiL5jzXoa6KGCuZGv7Cav3FRLXIjIdxw-z_7A.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=8f7e7129f159247782fa2e35ddaf503c",
"width": 320,
"height": 240
},
{
"url": "https://i.redditmedia.com/my7Y2tDiL5jzXoa6KGCuZGv7Cav3FRLXIjIdxw-z_7A.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=fa06b5fa6fb10229d88e71a64dbaae9c",
"width": 640,
"height": 480
},
{
"url": "https://i.redditmedia.com/my7Y2tDiL5jzXoa6KGCuZGv7Cav3FRLXIjIdxw-z_7A.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=5db534585bcf0ed9994a6843921ba342",
"width": 960,
"height": 720
},
{
"url": "https://i.redditmedia.com/my7Y2tDiL5jzXoa6KGCuZGv7Cav3FRLXIjIdxw-z_7A.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=f9d82884503059c23dd6194c5f2d65c7",
"width": 1080,
"height": 810
}
],
"variants": {},
"id": "E2QH-raR4YjfsKmQt-Y8Ws2SMqt4FSQ2SSa7BUNS4rI"
}
]
},
"num_comments": 6,
"thumbnail": "http://b.thumbs.redditmedia.com/-JCgUR8HsOLbQ5rcwiX9Yh4enoIcZ1_LOXFz1JZEcNI.jpg",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"post_hint": "link",
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/45tkc0/north_charleston_attempted_robber_shot_with_own/",
"locked": false,
"name": "t3_45tkc0",
"created": 1455520307,
"url": "http://counton2.com/2016/02/06/north-charleston-attempted-robber-shot-with-own-gun-by-victim-police-say/",
"author_flair_text": null,
"quarantine": false,
"title": "North Charleston attempted robber shot with own gun by victim",
"created_utc": 1455491507,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 29
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;My wife and I recently moved to the Charleston area, West Ashley more specifically, from southern California and are looking to meet some new people. We&amp;#39;re both 22 and are pretty social people. We have a few friends but mostly work friends.&lt;/p&gt;\n\n&lt;p&gt;As far as hobbies go, I like to read, play video games, play some MTG and other card games, tabletop games, cycle and run, draw and play guitar. My wife enjoys watching movies, also playing some tabletop games, painting, throwing clay, swimming, and eating sushi (god she loves sushi). &lt;/p&gt;\n\n&lt;p&gt;We&amp;#39;re really just looking to meet like minded people who don&amp;#39;t mind relaxing, talking and hanging out but also getting out and exploring the city and planning small outings. PM me if we sound interesting!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "My wife and I recently moved to the Charleston area, West Ashley more specifically, from southern California and are looking to meet some new people. We're both 22 and are pretty social people. We have a few friends but mostly work friends.\n\nAs far as hobbies go, I like to read, play video games, play some MTG and other card games, tabletop games, cycle and run, draw and play guitar. My wife enjoys watching movies, also playing some tabletop games, painting, throwing clay, swimming, and eating sushi (god she loves sushi). \n\nWe're really just looking to meet like minded people who don't mind relaxing, talking and hanging out but also getting out and exploring the city and planning small outings. PM me if we sound interesting!",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45u989",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "crazwomanyo",
"media": null,
"score": 11,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 8,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/45u989/new_to_the_area_looking_to_meet_people/",
"locked": false,
"name": "t3_45u989",
"created": 1455530778,
"url": "https://www.reddit.com/r/Charleston/comments/45u989/new_to_the_area_looking_to_meet_people/",
"author_flair_text": null,
"quarantine": false,
"title": "New to the area, looking to meet people!",
"created_utc": 1455501978,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 11
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I&amp;#39;ve seen quite a few turn lanes, particularly in the North Charleston area, which have solid red light right arrows at which I see many people treat as yield signs and others do not turn at all, causing much confusion. How is it different from a regular red light? How is it different from a solid red light &lt;em&gt;left&lt;/em&gt; arrow? Is there any difference for two right turn lanes?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I've seen quite a few turn lanes, particularly in the North Charleston area, which have solid red light right arrows at which I see many people treat as yield signs and others do not turn at all, causing much confusion. How is it different from a regular red light? How is it different from a solid red light *left* arrow? Is there any difference for two right turn lanes?",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45s3cb",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "burrbro235",
"media": null,
"score": 19,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 31,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/45s3cb/charlestonians_a_solid_red_light_right_arrow_at_a/",
"locked": false,
"name": "t3_45s3cb",
"created": 1455502328,
"url": "https://www.reddit.com/r/Charleston/comments/45s3cb/charlestonians_a_solid_red_light_right_arrow_at_a/",
"author_flair_text": null,
"quarantine": false,
"title": "Charlestonians, a solid red light right arrow at a right turn lane: what does it mean for you?",
"created_utc": 1455473528,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 19
}
},
{
"kind": "t3",
"data": {
"domain": "postandcourier.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45n4z1",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "JosephLucid",
"media": null,
"score": 11,
"approved_by": null,
"over_18": false,
"hidden": false,
"preview": {
"images": [
{
"source": {
"url": "https://i.redditmedia.com/ABSa2w4rvyFGX0LrgwlLv9mjJVlRVTaYj3qBtMkRhPU.jpg?s=a0646d64a11280761b8bbccda4840175",
"width": 2800,
"height": 1752
},
"resolutions": [
{
"url": "https://i.redditmedia.com/ABSa2w4rvyFGX0LrgwlLv9mjJVlRVTaYj3qBtMkRhPU.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=dfc47ad9288d417c373e2ff80048a498",
"width": 108,
"height": 67
},
{
"url": "https://i.redditmedia.com/ABSa2w4rvyFGX0LrgwlLv9mjJVlRVTaYj3qBtMkRhPU.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=a4398b1fa3b7bcabcafeb3a4f20ebb22",
"width": 216,
"height": 135
},
{
"url": "https://i.redditmedia.com/ABSa2w4rvyFGX0LrgwlLv9mjJVlRVTaYj3qBtMkRhPU.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=99dac1b8b0ab1517cbaf74b680a2b3da",
"width": 320,
"height": 200
},
{
"url": "https://i.redditmedia.com/ABSa2w4rvyFGX0LrgwlLv9mjJVlRVTaYj3qBtMkRhPU.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=35b6de4ff676da6c10fc58c6a3aaa6ea",
"width": 640,
"height": 400
},
{
"url": "https://i.redditmedia.com/ABSa2w4rvyFGX0LrgwlLv9mjJVlRVTaYj3qBtMkRhPU.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=004de45c69428660b606f3f85a805012",
"width": 960,
"height": 600
},
{
"url": "https://i.redditmedia.com/ABSa2w4rvyFGX0LrgwlLv9mjJVlRVTaYj3qBtMkRhPU.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=7ea6b38f0368b1f933d3aeac6fc22e47",
"width": 1080,
"height": 675
}
],
"variants": {},
"id": "awtP0ne83-BZRZ42HyRPHWQYDrLaiuy2V4Z7lbLLhtQ"
}
]
},
"num_comments": 3,
"thumbnail": "http://b.thumbs.redditmedia.com/UR8AQnZTQls6Pz6TrakVwRgR-ClmO0msnwaAfEIlAzg.jpg",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"post_hint": "link",
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/45n4z1/oriental_garden_closed/",
"locked": false,
"name": "t3_45n4z1",
"created": 1455431854,
"url": "http://www.postandcourier.com/article/20160211/PC05/160219830",
"author_flair_text": null,
"quarantine": false,
"title": "Oriental Garden Closed",
"created_utc": 1455403054,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 11
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Having recently changed branches to the USAF from the USMC, I have to get my new uniforms tailored, but have no clue where to go. As of now I have 20 days to get them done before my first report date so any advice would be great. I should note that in addition to getting rank put on I also need hemming done and some fabric taken in. Thanks in advance!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Having recently changed branches to the USAF from the USMC, I have to get my new uniforms tailored, but have no clue where to go. As of now I have 20 days to get them done before my first report date so any advice would be great. I should note that in addition to getting rank put on I also need hemming done and some fabric taken in. Thanks in advance!",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45lrea",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "rwaec4447",
"media": null,
"score": 14,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 7,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/45lrea/a_question_about_tailoring_in_the_chuck/",
"locked": false,
"name": "t3_45lrea",
"created": 1455415724,
"url": "https://www.reddit.com/r/Charleston/comments/45lrea/a_question_about_tailoring_in_the_chuck/",
"author_flair_text": null,
"quarantine": false,
"title": "A Question About Tailoring In The Chuck",
"created_utc": 1455386924,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 14
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Me and my husband are spending the night in Charleston and I was looking for a comedy club or maybe a burlesque show or a great bar to go to. But my knowledge of Charleston is limited so what would be some fun places to go to? Any suggestions is greatly appreciated&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Me and my husband are spending the night in Charleston and I was looking for a comedy club or maybe a burlesque show or a great bar to go to. But my knowledge of Charleston is limited so what would be some fun places to go to? Any suggestions is greatly appreciated",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45mhvc",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "hiddenbehindamask",
"media": null,
"score": 3,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 9,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/45mhvc/spending_the_night_in_charleston_and_looking_for/",
"locked": false,
"name": "t3_45mhvc",
"created": 1455424752,
"url": "https://www.reddit.com/r/Charleston/comments/45mhvc/spending_the_night_in_charleston_and_looking_for/",
"author_flair_text": null,
"quarantine": false,
"title": "Spending the night in Charleston and looking for things to do",
"created_utc": 1455395952,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 3
}
},
{
"kind": "t3",
"data": {
"domain": "photojambo.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45kc3e",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "spangard",
"media": null,
"score": 9,
"approved_by": null,
"over_18": false,
"hidden": false,
"preview": {
"images": [
{
"source": {
"url": "https://i.redditmedia.com/jqdHY6FkEodhr0rpdAAivjzgx3enplGDbLv24TeCgAE.jpg?s=a5c3375c48dac60a781eb6716af0e585",
"width": 1000,
"height": 562
},
"resolutions": [
{
"url": "https://i.redditmedia.com/jqdHY6FkEodhr0rpdAAivjzgx3enplGDbLv24TeCgAE.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=9dc1dbc0dfd4e096f3472e4e07320e65",
"width": 108,
"height": 60
},
{
"url": "https://i.redditmedia.com/jqdHY6FkEodhr0rpdAAivjzgx3enplGDbLv24TeCgAE.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=2be67804f25bb8d61819af0fe0cf94e7",
"width": 216,
"height": 121
},
{
"url": "https://i.redditmedia.com/jqdHY6FkEodhr0rpdAAivjzgx3enplGDbLv24TeCgAE.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=24a34b49ece5f5d848ed7496c3878319",
"width": 320,
"height": 179
},
{
"url": "https://i.redditmedia.com/jqdHY6FkEodhr0rpdAAivjzgx3enplGDbLv24TeCgAE.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=23360f254bbfff44492efdcc39ae924b",
"width": 640,
"height": 359
},
{
"url": "https://i.redditmedia.com/jqdHY6FkEodhr0rpdAAivjzgx3enplGDbLv24TeCgAE.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=42a239bfa34b849486b023c57e922450",
"width": 960,
"height": 539
}
],
"variants": {},
"id": "e1VVvWERs2kMYUzqOpoIX7LcyeB1YouQJDVE9-AFBic"
}
]
},
"num_comments": 2,
"thumbnail": "http://b.thumbs.redditmedia.com/Gqt5fSKjzDwlZ9YD_3fGUvbzfRvENNWZgKehzZFYr2U.jpg",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"post_hint": "link",
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/45kc3e/drone_photo_last_light_over_boneyard_beach_capers/",
"locked": false,
"name": "t3_45kc3e",
"created": 1455399240,
"url": "http://photojambo.com/photography/2016/last-light-over-boneyard-beach",
"author_flair_text": null,
"quarantine": false,
"title": "Drone Photo: Last Light Over Boneyard Beach (Capers Island)",
"created_utc": 1455370440,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 9
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Cops with guns out and lots of ambulances way down 17s near that harvest moon restaurant. Anyone know whats going on?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Cops with guns out and lots of ambulances way down 17s near that harvest moon restaurant. Anyone know whats going on?",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45iiw8",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Great_Shark_Hunter",
"media": null,
"score": 8,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 1,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/45iiw8/cops_witha_guns_out/",
"locked": false,
"name": "t3_45iiw8",
"created": 1455363384,
"url": "https://www.reddit.com/r/Charleston/comments/45iiw8/cops_witha_guns_out/",
"author_flair_text": null,
"quarantine": false,
"title": "Cops witha guns out...",
"created_utc": 1455334584,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 8
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hello, &lt;/p&gt;\n\n&lt;p&gt;Is anyone here familiar with Bellwright Manufacturing in Summerville?  I see online they make cnc parts for automotive manufacturers and that they are recovering from bankruptcy circa 2007-8.  Have the new owners turned the operation around?  Anybody worked with or used their products before?  Any feedback is appreciated as I am looking into working with them.  &lt;/p&gt;\n\n&lt;p&gt;Thanks&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Hello, \n\nIs anyone here familiar with Bellwright Manufacturing in Summerville?  I see online they make cnc parts for automotive manufacturers and that they are recovering from bankruptcy circa 2007-8.  Have the new owners turned the operation around?  Anybody worked with or used their products before?  Any feedback is appreciated as I am looking into working with them.  \n\nThanks\n",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45ge67",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "dirtyseaotter",
"media": null,
"score": 8,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 1,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/45ge67/inquiry_about_bellwright_manufacturing/",
"locked": false,
"name": "t3_45ge67",
"created": 1455334287,
"url": "https://www.reddit.com/r/Charleston/comments/45ge67/inquiry_about_bellwright_manufacturing/",
"author_flair_text": null,
"quarantine": false,
"title": "Inquiry about Bellwright Manufacturing",
"created_utc": 1455305487,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 8
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;First - To the mods.&lt;/p&gt;\n\n&lt;p&gt;I realize this is a fine line on &amp;quot;self promotion&amp;quot; but there is gain for all parties to be had.  However, if it is not a welcomed post, please by all means, remove it.&lt;/p&gt;\n\n&lt;p&gt;Secondly - To everyone Else.&lt;/p&gt;\n\n&lt;p&gt;If you have been interested in driving for Uber but needed a better reason how does an extra $500 in your pocket sound?&lt;/p&gt;\n\n&lt;p&gt;They&amp;#39;re currently offering that kick-back upon referral for new drivers.  It does depend on your residing address if you&amp;#39;ll receive that much (Mt. Pleasant pays $300 for instance..) but at the minimum you&amp;#39;ll scoop up $150.&lt;/p&gt;\n\n&lt;p&gt;All you have to do is sign up and hit the road.  After a X trips (no more then 30) in X days (no less than 20) you&amp;#39;ll be rewarded.&lt;/p&gt;\n\n&lt;p&gt;Interested?  Send me a private message and we can get the ball rolling.. &lt;/p&gt;\n\n&lt;p&gt;Toodaloo!&lt;/p&gt;\n\n&lt;p&gt;Edit:  In case it wasn&amp;#39;t clear, you&amp;#39;ll need my referral link.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "First - To the mods.\n\nI realize this is a fine line on \"self promotion\" but there is gain for all parties to be had.  However, if it is not a welcomed post, please by all means, remove it.\n\nSecondly - To everyone Else.\n\nIf you have been interested in driving for Uber but needed a better reason how does an extra $500 in your pocket sound?\n\nThey're currently offering that kick-back upon referral for new drivers.  It does depend on your residing address if you'll receive that much (Mt. Pleasant pays $300 for instance..) but at the minimum you'll scoop up $150.\n\nAll you have to do is sign up and hit the road.  After a X trips (no more then 30) in X days (no less than 20) you'll be rewarded.\n\nInterested?  Send me a private message and we can get the ball rolling.. \n\nToodaloo!\n\nEdit:  In case it wasn't clear, you'll need my referral link.",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45ht7v",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Agronopolopogis",
"media": null,
"score": 0,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 7,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": 1455328674,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/45ht7v/uber_is_offering_a_nice_kickback_to_new_drivers/",
"locked": false,
"name": "t3_45ht7v",
"created": 1455352522,
"url": "https://www.reddit.com/r/Charleston/comments/45ht7v/uber_is_offering_a_nice_kickback_to_new_drivers/",
"author_flair_text": null,
"quarantine": false,
"title": "Uber is offering a nice kick-back to new drivers!",
"created_utc": 1455323722,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 0
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Anyone know where there are any photo booths in or around Charleston? Bars, restaurants, movie theater?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Anyone know where there are any photo booths in or around Charleston? Bars, restaurants, movie theater?\n\n",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45cqms",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "N3WPORT",
"media": null,
"score": 10,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 6,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": 1455248394,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/45cqms/photo_booth_locations/",
"locked": false,
"name": "t3_45cqms",
"created": 1455275734,
"url": "https://www.reddit.com/r/Charleston/comments/45cqms/photo_booth_locations/",
"author_flair_text": null,
"quarantine": false,
"title": "Photo booth locations?",
"created_utc": 1455246934,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 10
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I&amp;#39;m currently looking for an engineering position in Charleston. Could anybody provide feedback on some of the businesses in the area? Who is a good employer and who isn&amp;#39;t? Thanks!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I'm currently looking for an engineering position in Charleston. Could anybody provide feedback on some of the businesses in the area? Who is a good employer and who isn't? Thanks!",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45ak8f",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "noshoesforyou",
"media": null,
"score": 8,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 29,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/45ak8f/best_place_to_work/",
"locked": false,
"name": "t3_45ak8f",
"created": 1455247518,
"url": "https://www.reddit.com/r/Charleston/comments/45ak8f/best_place_to_work/",
"author_flair_text": null,
"quarantine": false,
"title": "Best Place to Work?",
"created_utc": 1455218718,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 8
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;so, ive been offered a great opportunity at a dealership in Charleston and im having trouble shopping for places. if anyone has some insight on where would be a good place for me and my wife to live i would really appreciate the help.&lt;/p&gt;\n\n&lt;p&gt;every decently priced apartment is littered with bad reviews and we are getting stressed. in or on the outskirts of Charleston is great and any help is appreciated, thank you&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "so, ive been offered a great opportunity at a dealership in Charleston and im having trouble shopping for places. if anyone has some insight on where would be a good place for me and my wife to live i would really appreciate the help.\n\nevery decently priced apartment is littered with bad reviews and we are getting stressed. in or on the outskirts of Charleston is great and any help is appreciated, thank you",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45d49p",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "IamThe_stg",
"media": null,
"score": 0,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 9,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/45d49p/a_little_help_with_housing_please/",
"locked": false,
"name": "t3_45d49p",
"created": 1455281271,
"url": "https://www.reddit.com/r/Charleston/comments/45d49p/a_little_help_with_housing_please/",
"author_flair_text": null,
"quarantine": false,
"title": "a little help with housing please!!",
"created_utc": 1455252471,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 0
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;We&amp;#39;re hoping to move-in sometime in may or late april. As of now I&amp;#39;m loving Mt. Pleasant and I make ok money (60k). I really only need a 1bdr 1 bath and keeping it between $1000-1200. Any suggestions? I&amp;#39;m try to live in at the Haven at Midtown apartments as its one of the only nicer places that allows big dogs. Also any other good tips for fun? we&amp;#39;re 22 but we don&amp;#39;t drink, we might start picking up camping. Also race has never been an issue but i come from LA, any places I should stay clear from like the ghetto or certain bars? I&amp;#39;m mexican and she&amp;#39;s white, I don&amp;#39;t want to accidentally bring the wife into the wrong bar/place. &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "We're hoping to move-in sometime in may or late april. As of now I'm loving Mt. Pleasant and I make ok money (60k). I really only need a 1bdr 1 bath and keeping it between $1000-1200. Any suggestions? I'm try to live in at the Haven at Midtown apartments as its one of the only nicer places that allows big dogs. Also any other good tips for fun? we're 22 but we don't drink, we might start picking up camping. Also race has never been an issue but i come from LA, any places I should stay clear from like the ghetto or certain bars? I'm mexican and she's white, I don't want to accidentally bring the wife into the wrong bar/place. ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "45a1lw",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "StockArrow",
"media": null,
"score": 8,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 25,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/45a1lw/la_to_charleston_with_soon_to_be_wife_and_a/",
"locked": false,
"name": "t3_45a1lw",
"created": 1455241811,
"url": "https://www.reddit.com/r/Charleston/comments/45a1lw/la_to_charleston_with_soon_to_be_wife_and_a/",
"author_flair_text": null,
"quarantine": false,
"title": "LA to Charleston with soon to be Wife and a German Shepherd",
"created_utc": 1455213011,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 8
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hey all! Checked the wiki out but had a few specific questions (we will be staying in downtown Charleston): The bars listed in the wiki seem to be a ton of bar/pub type spots - are there any killer craft cocktail places?&lt;/p&gt;\n\n&lt;p&gt;What are the best coffee spots to get a good manually brewed cup? What are the best coffee spots to get a &lt;strong&gt;tiny&lt;/strong&gt; bit of work done (girlfriend is going to have to do ~1.5 hours of work)?&lt;/p&gt;\n\n&lt;p&gt;Incredibly excited to come to see your guys beautiful city! Thanks in advance.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Hey all! Checked the wiki out but had a few specific questions (we will be staying in downtown Charleston): The bars listed in the wiki seem to be a ton of bar/pub type spots - are there any killer craft cocktail places?\n\nWhat are the best coffee spots to get a good manually brewed cup? What are the best coffee spots to get a **tiny** bit of work done (girlfriend is going to have to do ~1.5 hours of work)?\n\nIncredibly excited to come to see your guys beautiful city! Thanks in advance.",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "4593k3",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "encinitastochicago",
"media": null,
"score": 4,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 20,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/4593k3/visiting_this_weekend_recommendations_on_cocktail/",
"locked": false,
"name": "t3_4593k3",
"created": 1455230995,
"url": "https://www.reddit.com/r/Charleston/comments/4593k3/visiting_this_weekend_recommendations_on_cocktail/",
"author_flair_text": null,
"quarantine": false,
"title": "Visiting this weekend - Recommendations on cocktail bars?",
"created_utc": 1455202195,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 4
}
},
{
"kind": "t3",
"data": {
"domain": "np.reddit.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "455uhv",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Malthepal",
"media": null,
"score": 31,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 5,
"thumbnail": "default",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/455uhv/xpost_from_sc_for_sanders_we_are_understaffed_in/",
"locked": false,
"name": "t3_455uhv",
"created": 1455177256,
"url": "https://np.reddit.com/r/SouthCarolina4Sanders/comments/453ivj/im_a_volunteer_at_the_sc_state_headquarters_in/",
"author_flair_text": null,
"quarantine": false,
"title": "(X-post from SC for Sanders) We are understaffed in our campaign office! Any volunteers are welcome to help the political revolutions!",
"created_utc": 1455148456,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 31
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I am visiting from Fl. There are a few places nearby which do Walking Dead screenings and I&amp;#39;d love to catch one in South SC. Any bars or theatres that do it here?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I am visiting from Fl. There are a few places nearby which do Walking Dead screenings and I'd love to catch one in South SC. Any bars or theatres that do it here?",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "456ykn",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "BertoneBeatle",
"media": null,
"score": 5,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 2,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/456ykn/walking_dead_screenings/",
"locked": false,
"name": "t3_456ykn",
"created": 1455192217,
"url": "https://www.reddit.com/r/Charleston/comments/456ykn/walking_dead_screenings/",
"author_flair_text": null,
"quarantine": false,
"title": "Walking Dead screenings?",
"created_utc": 1455163417,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 5
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Just heard from a friend in Chas that traffic is messed up because of Lots of &lt;strong&gt;Black SUV&lt;/strong&gt;s around Downtown and E Bay, So plan travels with time to spare this week folks!&lt;br/&gt;\nWho would it be? Everyone?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Just heard from a friend in Chas that traffic is messed up because of Lots of **Black SUV**s around Downtown and E Bay, So plan travels with time to spare this week folks!  \nWho would it be? Everyone?",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "455oea",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "ReproCompter",
"media": null,
"score": 14,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 15,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/455oea/the_black_suvs_are_in_charleston/",
"locked": false,
"name": "t3_455oea",
"created": 1455175134,
"url": "https://www.reddit.com/r/Charleston/comments/455oea/the_black_suvs_are_in_charleston/",
"author_flair_text": null,
"quarantine": false,
"title": "The Black SUVs are in Charleston",
"created_utc": 1455146334,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 14
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;They mention that Comcast is their internet provider, but I was wondering if anyone knew if WOW or something else was available?  I don&amp;#39;t want to deal with data caps on my internet.&lt;/p&gt;\n\n&lt;p&gt;Has anyone lived here before?  What&amp;#39;s it like?&lt;/p&gt;\n\n&lt;p&gt;Thanks guys&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "They mention that Comcast is their internet provider, but I was wondering if anyone knew if WOW or something else was available?  I don't want to deal with data caps on my internet.\n\nHas anyone lived here before?  What's it like?\n\nThanks guys",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "455gr9",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "buddiesels",
"media": null,
"score": 5,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 1,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/455gr9/thinking_about_moving_into_plantation_oaks/",
"locked": false,
"name": "t3_455gr9",
"created": 1455172552,
"url": "https://www.reddit.com/r/Charleston/comments/455gr9/thinking_about_moving_into_plantation_oaks/",
"author_flair_text": null,
"quarantine": false,
"title": "Thinking about moving into Plantation Oaks apartments in West Ashley. Anybody know anything about them?",
"created_utc": 1455143752,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 5
}
},
{
"kind": "t3",
"data": {
"domain": "photojambo.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "452qag",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "spangard",
"media": null,
"score": 18,
"approved_by": null,
"over_18": false,
"hidden": false,
"preview": {
"images": [
{
"source": {
"url": "https://i.redditmedia.com/gFmumMYtrsajb-AQNmBUiiHcMOjBI1xHTxO1nOWn82c.jpg?s=0afe12f6c6d0934d523487c9cde9dc14",
"width": 1000,
"height": 562
},
"resolutions": [
{
"url": "https://i.redditmedia.com/gFmumMYtrsajb-AQNmBUiiHcMOjBI1xHTxO1nOWn82c.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=937b5d21522f5d1badd2621382d7ed77",
"width": 108,
"height": 60
},
{
"url": "https://i.redditmedia.com/gFmumMYtrsajb-AQNmBUiiHcMOjBI1xHTxO1nOWn82c.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=fbc3622d541a0b998a9dfb20b0f374fa",
"width": 216,
"height": 121
},
{
"url": "https://i.redditmedia.com/gFmumMYtrsajb-AQNmBUiiHcMOjBI1xHTxO1nOWn82c.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=9006876ce6135d879f0067158e11d87e",
"width": 320,
"height": 179
},
{
"url": "https://i.redditmedia.com/gFmumMYtrsajb-AQNmBUiiHcMOjBI1xHTxO1nOWn82c.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=319097773785d36fafcf0276242c4be4",
"width": 640,
"height": 359
},
{
"url": "https://i.redditmedia.com/gFmumMYtrsajb-AQNmBUiiHcMOjBI1xHTxO1nOWn82c.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=7b07e38ba2c88615fcf014bf96a7c635",
"width": 960,
"height": 539
}
],
"variants": {},
"id": "YyW648kOmNJmxQSDwKCpfwUrHyWutKMAYN75dfbc-rU"
}
]
},
"num_comments": 2,
"thumbnail": "http://b.thumbs.redditmedia.com/Z-A6hf0v4CzKnRti2d3GPWSuNfNxYAbeKvCV1V3-RBo.jpg",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"post_hint": "link",
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/452qag/drone_photo_morning_haze_over_wild_dunes_yacht/",
"locked": false,
"name": "t3_452qag",
"created": 1455140447,
"url": "http://photojambo.com/photography/2016/morning-haze",
"author_flair_text": null,
"quarantine": false,
"title": "Drone Photo: Morning haze over Wild Dunes Yacht Harbor",
"created_utc": 1455111647,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 18
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Looking for a young professional or college student for a spare room in a 3bed2bath house off Ashley Phosphate.&lt;/p&gt;\n\n&lt;p&gt;&lt;a href=\"http://charleston.craigslist.org/roo/5442074283.html\"&gt;CL link&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Looking for a young professional or college student for a spare room in a 3bed2bath house off Ashley Phosphate.\n\n[CL link](http://charleston.craigslist.org/roo/5442074283.html)",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "454376",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "DaHispanicNinja",
"media": null,
"score": 5,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 0,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/454376/looking_for_roommate_in_north_charleston/",
"locked": false,
"name": "t3_454376",
"created": 1455156901,
"url": "https://www.reddit.com/r/Charleston/comments/454376/looking_for_roommate_in_north_charleston/",
"author_flair_text": null,
"quarantine": false,
"title": "Looking for roommate in North Charleston",
"created_utc": 1455128101,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 5
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hey, all my comcast services went down this morning around 11:30. I just called and was told there is an outage in the area (I&amp;#39;m currently in West Ashley). The estimated time I was told it would be repaired is around 4:00pm. I&amp;#39;m curious how wide spread the outage is, anyone else experiencing it?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Hey, all my comcast services went down this morning around 11:30. I just called and was told there is an outage in the area (I'm currently in West Ashley). The estimated time I was told it would be repaired is around 4:00pm. I'm curious how wide spread the outage is, anyone else experiencing it?",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "453uzf",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "dark_onewho",
"media": null,
"score": 3,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 4,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/453uzf/comcast_service_down_in_west_ashley/",
"locked": false,
"name": "t3_453uzf",
"created": 1455154355,
"url": "https://www.reddit.com/r/Charleston/comments/453uzf/comcast_service_down_in_west_ashley/",
"author_flair_text": null,
"quarantine": false,
"title": "Comcast service down in West Ashley",
"created_utc": 1455125555,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 3
}
}
],
"after": "t3_453uzf",
"before": null
}
}
